import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
    return (
        <>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <div className={styles.description}>

                    <h1>Ir al <a className={styles.title} href='/'>Home</a></h1>

                    <p>
                        Get started by editing&nbsp;
                        <code className={styles.code}>pages/index.tsx</code>
                    </p>
                </div>
            </main>
        </>
    )
}
